### ISSUE TITLE
Listing nearest NTRIP streams first ?

### ISSUE THREAD

**Issue by HJarausch** [ykasidit/bluetooth_gnss#14]
I have checked the _List nearest streams first_ checkbox.
But the first stream shown several thousands of kilometers apart.

( I have turned on GPS before s.t. my location is known)
What am I missing?

Thanks,
Helmut

**Comment by grinapo** [comment]
How often do you release on GooglePlay?

**Comment by ykasidit** [comment]
fyi, the fix is released on Google Play already now.

**Comment by Mikixie** [comment]
tried it and still with the problem,maybe I use it in China ?
![Screenshot_20211229-014139](https://user-images.githubusercontent.com/96790537/147593205-f57b61f1-3bf0-41c8-a7b9-45c50c69eede.jpg)
![Screenshot_20211229-014226](https://user-images.githubusercontent.com/96790537/147593210-b25ddce0-7a5f-4a7c-b3fa-0fe91fe9b1f8.jpg)

**Comment by ykasidit** [comment]
Hello, this sorting feature was confirmed working already now but it will work only if your caster sends location in its stream list (not 0,0). In your screenshot seems like the issue is with reading the stream. I might need the login and pass for the ntrip caster to test it - pls share via email to ykasidit@gmail.com if you want me to check further.

**Comment by ykasidit** [comment]
assume resolved
